### ISSUE TITLE
Error on .close()

### ISSUE THREAD

**Issue by WorldPosition** [nidorx/roblox-dat-gui#2]
`dat.GUI:185: attempt to index nil with 'Position'`

**Comment by nidorx** [comment]
Hello, can you send the full stack?

This error happened in the "Close Controls" button itself or when closing a folder

**Comment by WorldPosition** [comment]
Happened when I manually tried to call .close on the object the module returns. I fixed it by replacing line 185 with
`				if child["frame"] ~= nil then
					child.frame.Position = UDim2.new(0, 0, 0, pos)
				end`
Can't send full stack error because I removed the code that caused it

**Comment by nidorx** [comment]
Could not replicate, may have been resolved previously.

Tested in [v1.0.0](https://github.com/nidorx/roblox-dat-gui/releases/tag/v1.0.0)
