### ISSUE TITLE
Cannot open a closed folder until cursor touches valid Gui

### ISSUE THREAD

**Issue by incetents** [nidorx/roblox-dat-gui#3]
By default, until the cursor touches a working GUI element (number, string, checkbox, etc...) it is impossible to open or close any folders.

To easily recreate:
```
local gui = datGUI.new()
local gui_Info = gui.addFolder("Info")
gui_Info.close()

local gui_Data = {
    FPS = 0,
}
gui_Info.add(gui_Data, "FPS").readonly().listen()
```

You will notice that it is impossible to open the one closed folder from this point.

**Comment by nidorx** [comment]
Resolved in [v1.1](https://github.com/nidorx/roblox-dat-gui/releases/tag/v1.1)
