### ISSUE TITLE
Checkmarks cannot be on by default

### ISSUE THREAD

**Issue by incetents** [nidorx/roblox-dat-gui#4]
Any boolean values for your GUI will always have the checkmark start unchecked regardless if it's True/False.

After some quick searching in the code, it appears that it doesn't take into account the initial value for whether or not to draw a checkmark, only when it changes states.

**Comment by nidorx** [comment]
Resolved in [v1.0.0](https://github.com/nidorx/roblox-dat-gui/releases/tag/v1.0.0)
